// Datos iniciales migrados desde el proyecto Next.js.
// Se cargan a Google Sheets al ejecutar setupMinettiFutbol().

const SEED_CONFIG = [
  {
    "key": "APP_NAME",
    "value": "Minetti Fútbol"
  },
  {
    "key": "TOURNAMENT_NAME",
    "value": "Torneo Municipal de Fútbol de Menores 2026"
  },
  {
    "key": "ORGANIZER",
    "value": "Municipalidad Distrital de Pachacamac"
  },
  {
    "key": "VENUE",
    "value": "Estadio Sector B – Huertos de Manchay"
  },
  {
    "key": "PLAYER_PHOTOS_FOLDER_ID",
    "value": "PEGAR_AQUI_ID_CARPETA_DRIVE_IMG_JUGADORES"
  }
];
const SEED_CATEGORIES = [
  {
    "id": "sub6",
    "name": "Sub 6",
    "label": "6 años",
    "birthYears": "2020 – 2021",
    "minBirthYear": 2020,
    "maxBirthYear": 2021,
    "playersOnField": 7,
    "minPlayersOnField": 5,
    "gameTime": "15 - 15 minutos",
    "breakTime": "5 minutos"
  },
  {
    "id": "sub8",
    "name": "Sub 8",
    "label": "8 años",
    "birthYears": "2018 – 2019",
    "minBirthYear": 2018,
    "maxBirthYear": 2019,
    "playersOnField": 7,
    "minPlayersOnField": 5,
    "gameTime": "15 - 15 minutos",
    "breakTime": "5 minutos"
  },
  {
    "id": "sub10",
    "name": "Sub 10",
    "label": "10 años",
    "birthYears": "2016 – 2017",
    "minBirthYear": 2016,
    "maxBirthYear": 2017,
    "playersOnField": 9,
    "minPlayersOnField": 7,
    "gameTime": "15 - 15 minutos",
    "breakTime": "5 minutos"
  },
  {
    "id": "sub12",
    "name": "Sub 12",
    "label": "12 años",
    "birthYears": "2014 – 2015",
    "minBirthYear": 2014,
    "maxBirthYear": 2015,
    "playersOnField": 9,
    "minPlayersOnField": 7,
    "gameTime": "20 - 20 minutos",
    "breakTime": "5 minutos"
  }
];
const SEED_TEAMS = [
  {
    "teamId": "sub6-jm-sport-1",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "name": "JM SPORT",
    "active": "SI"
  },
  {
    "teamId": "sub6-tolentino-fc-2",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "name": "TOLENTINO FC",
    "active": "SI"
  },
  {
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "name": "GUERREROS DE MANCHAY",
    "active": "SI"
  },
  {
    "teamId": "sub6-club-deportivo-lara-4",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "name": "CLUB DEPORTIVO LARA",
    "active": "SI"
  },
  {
    "teamId": "sub6-renace-juventud-5",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "name": "RENACE JUVENTUD",
    "active": "SI"
  },
  {
    "teamId": "sub6-benjamin-fc-6",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "name": "BENJAMIN FC",
    "active": "SI"
  },
  {
    "teamId": "sub8-tolentino-fc-7",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO A",
    "name": "TOLENTINO FC",
    "active": "SI"
  },
  {
    "teamId": "sub8-fova-8",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO A",
    "name": "FOVA",
    "active": "SI"
  },
  {
    "teamId": "sub8-jyb-9",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO A",
    "name": "JYB",
    "active": "SI"
  },
  {
    "teamId": "sub8-dream-team-10",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO A",
    "name": "DREAM TEAM",
    "active": "SI"
  },
  {
    "teamId": "sub8-renace-juventud-11",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO A",
    "name": "RENACE JUVENTUD",
    "active": "SI"
  },
  {
    "teamId": "sub8-jm-sport-12",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO A",
    "name": "JM SPORT",
    "active": "SI"
  },
  {
    "teamId": "sub8-benjamin-fc-13",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO B",
    "name": "BENJAMIN FC",
    "active": "SI"
  },
  {
    "teamId": "sub8-vasquez-fc-14",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO B",
    "name": "VASQUEZ FC",
    "active": "SI"
  },
  {
    "teamId": "sub8-remanente-fc-15",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO B",
    "name": "REMANENTE FC",
    "active": "SI"
  },
  {
    "teamId": "sub8-guerreros-de-manchay-16",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO B",
    "name": "GUERREROS DE MANCHAY",
    "active": "SI"
  },
  {
    "teamId": "sub8-mathe-sport-17",
    "categoryId": "sub8",
    "categoryName": "Sub 8",
    "group": "GRUPO B",
    "name": "MATHE SPORT",
    "active": "SI"
  },
  {
    "teamId": "sub10-mathe-sport-18",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO A",
    "name": "MATHE SPORT",
    "active": "SI"
  },
  {
    "teamId": "sub10-fova-19",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO A",
    "name": "FOVA",
    "active": "SI"
  },
  {
    "teamId": "sub10-talentos-del-sur-20",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO A",
    "name": "TALENTOS DEL SUR",
    "active": "SI"
  },
  {
    "teamId": "sub10-remanente-fc-21",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO A",
    "name": "REMANENTE FC",
    "active": "SI"
  },
  {
    "teamId": "sub10-sporting-jf-once-22",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO A",
    "name": "SPORTING JF ONCE",
    "active": "SI"
  },
  {
    "teamId": "sub10-renace-juventud-23",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO A",
    "name": "RENACE JUVENTUD",
    "active": "SI"
  },
  {
    "teamId": "sub10-benjamin-fc-24",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO A",
    "name": "BENJAMIN FC",
    "active": "SI"
  },
  {
    "teamId": "sub10-guerreros-de-manchay-25",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO B",
    "name": "GUERREROS DE MANCHAY",
    "active": "SI"
  },
  {
    "teamId": "sub10-vasquez-fc-26",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO B",
    "name": "VASQUEZ FC",
    "active": "SI"
  },
  {
    "teamId": "sub10-jm-sport-27",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO B",
    "name": "JM SPORT",
    "active": "SI"
  },
  {
    "teamId": "sub10-tolentino-fc-28",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO B",
    "name": "TOLENTINO FC",
    "active": "SI"
  },
  {
    "teamId": "sub10-talentos-unidos-29",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO B",
    "name": "TALENTOS UNIDOS",
    "active": "SI"
  },
  {
    "teamId": "sub10-dream-team-30",
    "categoryId": "sub10",
    "categoryName": "Sub 10",
    "group": "GRUPO B",
    "name": "DREAM TEAM",
    "active": "SI"
  },
  {
    "teamId": "sub12-guerreros-de-manchay-31",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO A",
    "name": "GUERREROS DE MANCHAY",
    "active": "SI"
  },
  {
    "teamId": "sub12-tolentino-fc-32",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO A",
    "name": "TOLENTINO FC",
    "active": "SI"
  },
  {
    "teamId": "sub12-mathe-sport-33",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO A",
    "name": "MATHE SPORT",
    "active": "SI"
  },
  {
    "teamId": "sub12-sporting-jf-once-34",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO A",
    "name": "SPORTING JF ONCE",
    "active": "SI"
  },
  {
    "teamId": "sub12-fova-35",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO A",
    "name": "FOVA",
    "active": "SI"
  },
  {
    "teamId": "sub12-jyb-36",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO A",
    "name": "JYB",
    "active": "SI"
  },
  {
    "teamId": "sub12-benjamin-fc-37",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO A",
    "name": "BENJAMIN FC",
    "active": "SI"
  },
  {
    "teamId": "sub12-renace-juventud-38",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO B",
    "name": "RENACE JUVENTUD",
    "active": "SI"
  },
  {
    "teamId": "sub12-jm-sport-39",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO B",
    "name": "JM SPORT",
    "active": "SI"
  },
  {
    "teamId": "sub12-talentos-unidos-40",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO B",
    "name": "TALENTOS UNIDOS",
    "active": "SI"
  },
  {
    "teamId": "sub12-dream-team-41",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO B",
    "name": "DREAM TEAM",
    "active": "SI"
  },
  {
    "teamId": "sub12-club-deportivo-lara-42",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO B",
    "name": "CLUB DEPORTIVO LARA",
    "active": "SI"
  },
  {
    "teamId": "sub12-cachorros-fc-43",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO B",
    "name": "CACHORROS FC",
    "active": "SI"
  },
  {
    "teamId": "sub12-fovita-44",
    "categoryId": "sub12",
    "categoryName": "Sub 12",
    "group": "GRUPO B",
    "name": "FOVITA",
    "active": "SI"
  }
];
const SEED_FIXTURE = [
  {
    "id": "cal-1",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 1",
    "time": "09:00",
    "categoryId": "sub6",
    "categoryLabel": "SUB 6",
    "group": "Único",
    "home": "JM SPORT",
    "away": "RENACE JUVENTUD",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 2,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-2",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 1",
    "time": "09:40",
    "categoryId": "sub6",
    "categoryLabel": "SUB 6",
    "group": "Único",
    "home": "BENJAMIN FC",
    "away": "CLUB DEPORTIVO LARA",
    "status": "jugado",
    "homeScore": 0,
    "awayScore": 2,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-3",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 1",
    "time": "10:20",
    "categoryId": "sub6",
    "categoryLabel": "SUB 6",
    "group": "Único",
    "home": "TOLENTINO FC",
    "away": "GUERREROS DE MANCHAY",
    "status": "jugado",
    "homeScore": 0,
    "awayScore": 4,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-4",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 1",
    "time": "11:00",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (A)",
    "group": "GRUPO A",
    "home": "JYB",
    "away": "DREAM TEAM",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-5",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "09:00",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (B)",
    "group": "GRUPO B",
    "home": "BENJAMIN FC",
    "away": "MATHE SPORT",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 3,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-6",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "09:40",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "JM SPORT",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 4,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-7",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "10:20",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "RENACE JUVENTUD",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-8",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "11:00",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (B)",
    "group": "GRUPO B",
    "home": "VASQUEZ FC",
    "away": "GUERREROS DE MANCHAY",
    "status": "jugado",
    "homeScore": 0,
    "awayScore": 6,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-9",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "12:00",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (B)",
    "group": "GRUPO B",
    "home": "VASQUEZ FC",
    "away": "TALENTOS UNIDOS",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 4,
    "resultType": "normal",
    "note": "Marcador transcrito desde imagen: se interpreta VASQUEZ FC 1 - 4 TALENTOS UNIDOS."
  },
  {
    "id": "cal-10",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "12:50",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (B)",
    "group": "GRUPO B",
    "home": "GUERREROS DE MANCHAY",
    "away": "DREAM TEAM",
    "status": "jugado",
    "homeScore": 5,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-11",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "13:40",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (B)",
    "group": "GRUPO B",
    "home": "JM SPORT",
    "away": "TOLENTINO FC",
    "status": "jugado",
    "homeScore": 3,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-12",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 2",
    "time": "14:30",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "BENJAMIN FC",
    "status": "jugado",
    "homeScore": 6,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-13",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "09:00",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (B)",
    "group": "GRUPO B",
    "home": "DREAM TEAM",
    "away": "CLUB DEPORTIVO LARA",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 0,
    "resultType": "wo",
    "note": "DREAM TEAM ganó por W.O.; para tabla se registra 2-0."
  },
  {
    "id": "cal-14",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "09:50",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "JYB",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 3,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-15",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "10:40",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (A)",
    "group": "GRUPO A",
    "home": "SPORTING JF ONCE",
    "away": "FOVA",
    "status": "jugado",
    "homeScore": 4,
    "awayScore": 2,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-16",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "11:30",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (B)",
    "group": "GRUPO B",
    "home": "JM SPORT",
    "away": "FOVITA",
    "status": "jugado",
    "homeScore": 5,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-17",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "12:20",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (A)",
    "group": "GRUPO A",
    "home": "TALENTOS DEL SUR",
    "away": "SPORTING JF ONCE",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-18",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "13:10",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "BENJAMIN FC",
    "status": "jugado",
    "homeScore": 5,
    "awayScore": 2,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-19",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "14:00",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (B)",
    "group": "GRUPO B",
    "home": "TALENTOS UNIDOS",
    "away": "CACHORROS FC",
    "status": "jugado",
    "homeScore": 3,
    "awayScore": 2,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-20",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "CAMPO 3",
    "time": "14:50",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "RENACE JUVENTUD",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 5,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-21",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA REMANENTE FC SUB 8 (B)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "cal-22",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA REMANENTE FC SUB 10 (A)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "cal-23",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA GUERREROS DE MANCHAY SUB 12 (A)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "cal-24",
    "dateLabel": "17 DE MAYO FECHA 1",
    "round": 1,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA RENACE JUVENTUD SUB 12 (B)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "cal-25",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 1",
    "time": "09:00",
    "categoryId": "sub6",
    "categoryLabel": "SUB 6",
    "group": "Único",
    "home": "RENACE JUVENTUD",
    "away": "GUERREROS DE MANCHAY",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-26",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 1",
    "time": "09:40",
    "categoryId": "sub6",
    "categoryLabel": "SUB 6",
    "group": "Único",
    "home": "TOLENTINO FC",
    "away": "BENJAMIN FC",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 2,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-27",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 1",
    "time": "10:20",
    "categoryId": "sub6",
    "categoryLabel": "SUB 6",
    "group": "Único",
    "home": "JM SPORT",
    "away": "CLUB DEPORTIVO LARA",
    "status": "jugado",
    "homeScore": 0,
    "awayScore": 2,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-28",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 1",
    "time": "11:00",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (A)",
    "group": "GRUPO A",
    "home": "JM SPORT",
    "away": "DREAM TEAM",
    "status": "jugado",
    "homeScore": 4,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-29",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "09:00",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "RENACE JUVENTUD",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 4,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-30",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "09:40",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (B)",
    "group": "GRUPO B",
    "home": "MATHE SPORT",
    "away": "REMANENTE FC",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 5,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-31",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "10:20",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (B)",
    "group": "GRUPO B",
    "home": "BENJAMIN FC",
    "away": "GUERREROS DE MANCHAY",
    "status": "jugado",
    "homeScore": 0,
    "awayScore": 6,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-32",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "11:00",
    "categoryId": "sub8",
    "categoryLabel": "SUB 8 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "JYB",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-33",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "12:00",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (B)",
    "group": "GRUPO B",
    "home": "GUERREROS DE MANCHAY",
    "away": "TALENTOS UNIDOS",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-34",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "12:50",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (B)",
    "group": "GRUPO B",
    "home": "VASQUEZ FC",
    "away": "JM SPORT",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 3,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-35",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "13:40",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (A)",
    "group": "GRUPO A",
    "home": "BENJAMIN FC",
    "away": "REMANENTE FC",
    "status": "jugado",
    "homeScore": 0,
    "awayScore": 5,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-36",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 2",
    "time": "14:30",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "TALENTOS DEL SUR",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-37",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "09:00",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "FOVA",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-38",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "09:50",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (B)",
    "group": "GRUPO B",
    "home": "DREAM TEAM",
    "away": "TOLENTINO FC",
    "status": "jugado",
    "homeScore": 3,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-39",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "10:40",
    "categoryId": "sub10",
    "categoryLabel": "SUB 10 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "RENACE JUVENTUD",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-40",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "11:30",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (B)",
    "group": "GRUPO B",
    "home": "JM SPORT",
    "away": "CLUB DEPORTIVO LARA",
    "status": "jugado",
    "homeScore": 4,
    "awayScore": 3,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-41",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "12:20",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (B)",
    "group": "GRUPO B",
    "home": "RENACE JUVENTUD",
    "away": "FOVITA",
    "status": "jugado",
    "homeScore": 1,
    "awayScore": 5,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-42",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "13:10",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (A)",
    "group": "GRUPO A",
    "home": "GUERREROS DE MANCHAY",
    "away": "BENJAMIN FC",
    "status": "jugado",
    "homeScore": 2,
    "awayScore": 0,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-43",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "14:00",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "SPORTING JF ONCE",
    "status": "jugado",
    "homeScore": 0,
    "awayScore": 7,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-44",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "CAMPO 3",
    "time": "14:50",
    "categoryId": "sub12",
    "categoryLabel": "SUB 12 (B)",
    "group": "GRUPO B",
    "home": "TALENTOS UNIDOS",
    "away": "DREAM TEAM",
    "status": "jugado",
    "homeScore": 3,
    "awayScore": 1,
    "resultType": "normal",
    "note": ""
  },
  {
    "id": "cal-45",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA VASQUEZ FC SUB 8 (B)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "cal-46",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA SPORTING JF ONCE SUB 10 (A)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "cal-47",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA JYB SUB 12 (A)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "cal-48",
    "dateLabel": "24 DE MAYO FECHA 2",
    "round": 2,
    "field": "",
    "time": "",
    "categoryId": "",
    "categoryLabel": "",
    "group": "",
    "home": "DESCANSA CACHORROS FC SUB 12 (B)",
    "away": "",
    "status": "descansa",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-3-7",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "GUERREROS DE MANCHAY",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-4-8",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "JM SPORT",
    "away": "TOLENTINO FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-3-9",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "TOLENTINO FC",
    "away": "CLUB DEPORTIVO LARA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-4-10",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "BENJAMIN FC",
    "away": "GUERREROS DE MANCHAY",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-3-11",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "RENACE JUVENTUD",
    "away": "BENJAMIN FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-4-12",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "CLUB DEPORTIVO LARA",
    "away": "RENACE JUVENTUD",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-5-13",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "BENJAMIN FC",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-5-14",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "TOLENTINO FC",
    "away": "RENACE JUVENTUD",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub6-único-5-15",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub6",
    "categoryLabel": "Sub 6",
    "group": "Único",
    "home": "CLUB DEPORTIVO LARA",
    "away": "GUERREROS DE MANCHAY",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-3-7",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "DREAM TEAM",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-4-8",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "JYB",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-3-9",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "RENACE JUVENTUD",
    "away": "JYB",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-4-10",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "DREAM TEAM",
    "away": "FOVA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-3-11",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "JM SPORT",
    "away": "FOVA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-4-12",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "RENACE JUVENTUD",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-5-13",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "FOVA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-5-14",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "JYB",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-a-5-15",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (A)",
    "group": "GRUPO A",
    "home": "DREAM TEAM",
    "away": "RENACE JUVENTUD",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-b-3-22",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (B)",
    "group": "GRUPO B",
    "home": "BENJAMIN FC",
    "away": "REMANENTE FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-b-4-23",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (B)",
    "group": "GRUPO B",
    "home": "BENJAMIN FC",
    "away": "VASQUEZ FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-b-3-24",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (B)",
    "group": "GRUPO B",
    "home": "MATHE SPORT",
    "away": "VASQUEZ FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-b-4-25",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (B)",
    "group": "GRUPO B",
    "home": "REMANENTE FC",
    "away": "GUERREROS DE MANCHAY",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-b-5-28",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (B)",
    "group": "GRUPO B",
    "home": "REMANENTE FC",
    "away": "VASQUEZ FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub8-grupo-b-5-29",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub8",
    "categoryLabel": "Sub 8 (B)",
    "group": "GRUPO B",
    "home": "GUERREROS DE MANCHAY",
    "away": "MATHE SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-3-9",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "SPORTING JF ONCE",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-4-10",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "REMANENTE FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-3-11",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "RENACE JUVENTUD",
    "away": "TALENTOS DEL SUR",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-4-12",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "SPORTING JF ONCE",
    "away": "RENACE JUVENTUD",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-3-13",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "REMANENTE FC",
    "away": "FOVA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-4-14",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "BENJAMIN FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-5-17",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "TALENTOS DEL SUR",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-6-18",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "MATHE SPORT",
    "away": "FOVA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-5-19",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "REMANENTE FC",
    "away": "SPORTING JF ONCE",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-6-20",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "TALENTOS DEL SUR",
    "away": "REMANENTE FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-5-21",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "BENJAMIN FC",
    "away": "RENACE JUVENTUD",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-6-22",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "BENJAMIN FC",
    "away": "SPORTING JF ONCE",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-7-25",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "SPORTING JF ONCE",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-7-26",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "RENACE JUVENTUD",
    "away": "REMANENTE FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-a-7-27",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (A)",
    "group": "GRUPO A",
    "home": "BENJAMIN FC",
    "away": "TALENTOS DEL SUR",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-3-35",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "GUERREROS DE MANCHAY",
    "away": "TOLENTINO FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-4-36",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "GUERREROS DE MANCHAY",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-3-37",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "TALENTOS UNIDOS",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-4-38",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "TOLENTINO FC",
    "away": "VASQUEZ FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-3-39",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "DREAM TEAM",
    "away": "VASQUEZ FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-4-40",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "TALENTOS UNIDOS",
    "away": "DREAM TEAM",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-5-41",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "GUERREROS DE MANCHAY",
    "away": "VASQUEZ FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-5-42",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "JM SPORT",
    "away": "DREAM TEAM",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub10-grupo-b-5-43",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub10",
    "categoryLabel": "Sub 10 (B)",
    "group": "GRUPO B",
    "home": "TOLENTINO FC",
    "away": "TALENTOS UNIDOS",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-3-9",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "GUERREROS DE MANCHAY",
    "away": "JYB",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-4-10",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "GUERREROS DE MANCHAY",
    "away": "FOVA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-3-11",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "BENJAMIN FC",
    "away": "FOVA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-4-12",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "JYB",
    "away": "SPORTING JF ONCE",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-3-13",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "TOLENTINO FC",
    "away": "MATHE SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-4-14",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "BENJAMIN FC",
    "away": "MATHE SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-5-17",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "GUERREROS DE MANCHAY",
    "away": "SPORTING JF ONCE",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-6-18",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "GUERREROS DE MANCHAY",
    "away": "MATHE SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-5-19",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "MATHE SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-6-20",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "SPORTING JF ONCE",
    "away": "TOLENTINO FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-5-21",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "JYB",
    "away": "TOLENTINO FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-6-22",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "JYB",
    "away": "BENJAMIN FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-7-25",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "GUERREROS DE MANCHAY",
    "away": "TOLENTINO FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-7-26",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "SPORTING JF ONCE",
    "away": "BENJAMIN FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-a-7-27",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (A)",
    "group": "GRUPO A",
    "home": "FOVA",
    "away": "JYB",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-3-37",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "RENACE JUVENTUD",
    "away": "CACHORROS FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-4-38",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "RENACE JUVENTUD",
    "away": "CLUB DEPORTIVO LARA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-3-39",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "FOVITA",
    "away": "CLUB DEPORTIVO LARA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-4-40",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "CACHORROS FC",
    "away": "DREAM TEAM",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-3-41",
    "dateLabel": "FECHA 3",
    "round": 3,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "JM SPORT",
    "away": "TALENTOS UNIDOS",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-4-42",
    "dateLabel": "FECHA 4",
    "round": 4,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "FOVITA",
    "away": "TALENTOS UNIDOS",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-5-45",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "RENACE JUVENTUD",
    "away": "DREAM TEAM",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-6-46",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "RENACE JUVENTUD",
    "away": "TALENTOS UNIDOS",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-5-47",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "CLUB DEPORTIVO LARA",
    "away": "TALENTOS UNIDOS",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-6-48",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "DREAM TEAM",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-5-49",
    "dateLabel": "FECHA 5",
    "round": 5,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "CACHORROS FC",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-6-50",
    "dateLabel": "FECHA 6",
    "round": 6,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "CACHORROS FC",
    "away": "FOVITA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-7-53",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "RENACE JUVENTUD",
    "away": "JM SPORT",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-7-54",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "DREAM TEAM",
    "away": "FOVITA",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  },
  {
    "id": "sub12-grupo-b-7-55",
    "dateLabel": "FECHA 7",
    "round": 7,
    "field": "",
    "time": "",
    "categoryId": "sub12",
    "categoryLabel": "Sub 12 (B)",
    "group": "GRUPO B",
    "home": "CLUB DEPORTIVO LARA",
    "away": "CACHORROS FC",
    "status": "programado",
    "homeScore": "",
    "awayScore": "",
    "resultType": "",
    "note": ""
  }
];
const SEED_PLAYERS = [
  {
    "playerId": "guerreros-sub6-01",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Alexander Chanca Hernandez",
    "dni": "94768639",
    "birthDate": "2020-03-11",
    "birthYear": 2020,
    "status": "aprobado",
    "photoFileName": "94768639.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-02",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Victor Francesco De la Cruz Mego",
    "dni": "91972988",
    "birthDate": "2020-08-15",
    "birthYear": 2020,
    "status": "aprobado",
    "photoFileName": "91972988.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-03",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Liam Salcedo Mayta",
    "dni": "92523349",
    "birthDate": "2021-09-04",
    "birthYear": 2021,
    "status": "aprobado",
    "photoFileName": "92523349.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-04",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Liam Darhiel Chacón Vallejos",
    "dni": "92622043",
    "birthDate": "2021-11-11",
    "birthYear": 2021,
    "status": "aprobado",
    "photoFileName": "92622043.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-05",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Gianluca Aurelio Pariona Llanterguay",
    "dni": "92695777",
    "birthDate": "2021-01-04",
    "birthYear": 2021,
    "status": "aprobado",
    "photoFileName": "92695777.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-07",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Hans Steven Quispe Goitia",
    "dni": "91674980",
    "birthDate": "2020-01-10",
    "birthYear": 2020,
    "status": "aprobado",
    "photoFileName": "91674980.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-08",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Iker Joel Molleapaza Gutierrez",
    "dni": "91903581",
    "birthDate": "2020-06-23",
    "birthYear": 2020,
    "status": "aprobado",
    "photoFileName": "91903581.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-10",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Dylan Caleb Yajahuanca Arones",
    "dni": "91814200",
    "birthDate": "2020-04-14",
    "birthYear": 2020,
    "status": "aprobado",
    "photoFileName": "91814200.png",
    "photoUrl": ""
  },
  {
    "playerId": "guerreros-sub6-11",
    "teamId": "sub6-guerreros-de-manchay-3",
    "categoryId": "sub6",
    "categoryName": "Sub 6",
    "group": "Único",
    "teamName": "GUERREROS DE MANCHAY",
    "fullName": "Lucas Anuel Guevara Braco",
    "dni": "92094647",
    "birthDate": "2020-11-04",
    "birthYear": 2020,
    "status": "aprobado",
    "photoFileName": "92094647.png",
    "photoUrl": ""
  }
];
const SEED_DELEGATES = [
  {
    "token": "demo-guerreros-sub6",
    "delegateName": "Elvis Robles",
    "phone": "980953566",
    "teamId": "sub6-guerreros-de-manchay-3",
    "role": "delegado",
    "status": "activo"
  }
];
